# Generated by Django 6.0.3 on 2026-04-05 03:41

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': "Ce nom d'utilisateur est déjà pris."}, help_text='Requis. 150 caractères maximum. Lettres et espaces autorisés.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
