# Generated by Django 6.0.3 on 2026-03-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='est_archive',
            field=models.BooleanField(default=False),
        ),
    ]
